### ISSUE TITLE
Can this package be installed in ros-noetic?

### ISSUE THREAD

**Issue by lfj95** [knowrob/rosprolog#19]
My Ubuntu version is 20.04, so the correspondent ROS is ros-noetic. When I try install this rosprolog package with "sudo apt install ros-noetic-rosprolog", I got the following error:
E: Unable to locate package ros-noetic-rosprolog

Is this because the ROS version doesn't match? Is there an install instruction for this package?

**Comment by hawkina** [comment]
you should be able to pull it inside your repo and build it there localy. Please let us know if it does not work.

**Comment by jpcoffelt** [comment]
I have also had trouble installing rosprolog as part of the KnowRob install described [here](https://github.com/knowrob/knowrob).

This step:

`rosdep install --ignore-src --from-paths .`

returns this error message:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosprolog: No definition of [python-future] for OS version [focal]
```

However, cloning directly via

`git clone https://github.com/knowrob/rosprolog.git`

and then making seemed to work.

**Comment by hawkina** [comment]
I had the same. I went into the package xml and set python-future to python3-future. 
But then I got: 
rosprolog: No definition of [python-future] for OS version [focal]
Installed std-msgs and it was fine for some reason. Hope that helps.

**Comment by Rezenders** [comment]
This PR https://github.com/knowrob/rosprolog/pull/21 is a solution

**Comment by sasjonge** [comment]
Hi,

I have to apologize that I didn't close this issue earlier. There is a working noetic branch. We want to keep the master on noetic for now.

This issue was already fixed with PR https://github.com/knowrob/rosprolog/pull/20

**Comment by rebek254** [comment]
Sry for asking, but how is the installation of knowrob suposed to work. I use Ros Noetic on a Ubuntu 20.04 distro.
I'm not getting it. Still got the same error on the $_rosdep install --ignore-src --from-paths ._  command.
The error says:
_ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosprolog: No definition of [python-future] for OS version [focal]_

I tried the manual for installation from <https://github.com/artnie/knowrob>.
Aswell as a $_git clone_ of the noetic branch from rosprolog.

I keep getting this error again.

THX for help.

**Comment by sasjonge** [comment]
You seem to not use the noetic branch of rosprolog, because rosprolog doesn't contain python-future: https://github.com/knowrob/rosprolog/blob/noetic/package.xml

**Comment by rebek254** [comment]
okay thx for the quick answer i will doublecheck this.

**Comment by rebek254** [comment]
You were absolutely right. As is installed knowrob i unintentionally overwrote the noetic clone of rosprolog.
THX for help and very quick answers.
